typography_spectrum: 0.1285116858780384
color:
  brandStrength: 0.23890741518698633
  lightness: 0.5260518721770495
  saturation: 0.6886891934555024
  rhythmicContrast: 0.9536521893460304
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.7714424547739327
author:
  name: Bo Tel√©n Andersen
  email: bta@itoptimiser.com
name: My Blog about Collaboration
title: Collaboration in my view
